/**
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 * SEE THE COPYRIGHT FILE=' LICENSE.txt' DISTRIBUTED WITH THIS WORK FOR ADDITIONAL
 * INFORMATION REGARDING COPYRIGHT OWNERSHIP
 */
package com.dk.beans

case class DkJobHistory(orgCode: String, jobName: String, jobType: String,
    createdBy: String ) {
}

